//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeManagement.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using EmployeeManagement.Model;
    
    public partial class EmployeeDatabaseEntities : DbContext
    {
        public EmployeeDatabaseEntities()
            : base("name=EmployeeDatabaseEntities")
        {
        }
           
        public virtual DbSet<Employee> Employees { get; set; }
    }
}
